### ISSUE TITLE
Design interactive audit table

### ISSUE THREAD

**Issue by ChasNelson1990** [gliff-ai/audit#1]
We want a human-friendly, interactive interface for exploring a large and complex audit trail.

**Comment by joshuajames-smith** [comment]
[Work in Progress]
I've kept on with the previous styling from CURATE and MANAGE. Main audit table with search and navigation functionality to the left. As discussed, there is two filter options: 1) filter by each column and; 2) filter with a string search.

The user can click on the column heading to open a pop-up box with which they could filter by turning things on and off. Thinking a select all button would work here for each select/deselect all function. Possibly add another filter in here such as alphabet or date etc.

The user can create a string search as they can in CURATE. 

![Interface Layout v2 -  layout](https://user-images.githubusercontent.com/83074763/126814527-c3ea9cd1-721c-49ef-b85e-69cf72d6433e.png)
![Interface Layout v2 -  filter column](https://user-images.githubusercontent.com/83074763/126814534-cd4d689e-f111-4a37-ba66-9b9fc56cbab9.png)
![Interface Layout v2 -  filter string search](https://user-images.githubusercontent.com/83074763/126814542-6f91c4ef-f5a3-4475-953c-ac55b3574401.png)

**Comment by cooper667** [comment]
Because we have to load _all_ the data into memory to enable search, we _might_ want a couple of filters there by default, so we can load less data? 

I think date would make sense and possibly images to allow us to limit the amount of data we need to decrypt and load for searching? Not sure if we can do it by image, we might only be able to do it practically on audit metadata?

the example is a project level audit consisting of a million entries, if the user is only interested in the last few/last days worth, it seems inefficient to decrypt it all (as well as potentially very slow)

**Comment by ChasNelson1990** [comment]
bump #2
